on:
  workflow_dispatch:

env:
  NODE_VERSION: '10.x'                # set this to the node version to use
  PACKAGE_VERSION: '0.0.2-alpha'

jobs: 
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
        registry-url: 'https://registry.npmjs.org'
    - name: npm pack 
      run: |
        # install autorest
        Write-Output "running npm pack on sdk\Typescript\MetaPackage\Connectors-All"
        npm pack .\sdk\Typescript\MetaPackage\Connectors-All\
      shell: pwsh
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.401'
    - name: setup nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'
    - name: Build csharp and create nuget package
      run: |
        Write-Output "running nuget pack on sdk/CSharp/MetaPackage/NuspecFile/Microsoft.Azure.Connectors.All.${{ env.PACKAGE_VERSION }}.nuspec"
        nuget pack sdk/CSharp/MetaPackage/NuspecFile/Microsoft.Azure.Connectors.All.${{ env.PACKAGE_VERSION }}.nuspec
      shell: pwsh
    - name: Move package artifacts to out folder
      run: |
        # create out folder if it does not exist
        if(-not (Test-Path .\out -PathType Container))
        {
            New-Item -Path "." -Name "out" -ItemType "directory"
        }
        $version = "${{ env.PACKAGE_VERSION }}"
        # copy files to out folder
        New-Item -ItemType File -Path "./out/azure-apihub/typescript/$($version)/azure-connectors-all-${{ env.PACKAGE_VERSION }}.tgz" -Force
        Copy-Item -Path "./azure-connectors-all-${{ env.PACKAGE_VERSION }}.tgz" -Destination "./out/azure-apihub/typescript/$($version)/azure-connectors-all-${{ env.PACKAGE_VERSION }}.tgz" -Force

        New-Item -ItemType File -Path "./out/azure-apihub/csharp/$($version)/Microsoft.Azure.Connectors.All.${{ env.PACKAGE_VERSION }}.nupkg" -Force
        Copy-Item -Path "./Microsoft.Azure.Connectors.All.${{ env.PACKAGE_VERSION }}.nupkg" -Destination "./out/azure-apihub/csharp/$($version)/Microsoft.Azure.Connectors.All.${{ env.PACKAGE_VERSION }}.nupkg" -Force
      shell: pwsh
    - name: Upload output
      uses: actions/upload-artifact@v2
      with:
        name: out
        path: out
